// react/montyhall/src/main/App.jsx
import React, { Component } from "react"
import Porta from "../Components/Porta"

import './App.css'

export default class App extends Component {

    state = {
        jogoIniciado: false,
        totalDePortas: 3,
        portaSelecionada: null,
    }

    setTotalDePortas(e) {
        this.setState({ totalDePortas: e.target.value })
    }

    setPortaSelecionada(e) {
        this.setState({ portaSelecionada: e.target.value })

    }

    setJogoIniciado(e, iniciar) {
        e.preventDefault()
        this.setState({ jogoIniciado: iniciar })

    }

    renderizarPortas() {
        const portas = []
        for (let i = 1; i <= this.state.totalDePortas; i++) {
            portas.push(<Porta numero={i} index={i} premiada={this.state.portaSelecionada == i} />)
        }

        return portas.map((porta, index) => {
            return (
                porta
            )
        })
    }

    verificarEntradas(e){
        const portaSelecionada = parseFloat(this.state.portaSelecionada)
        const totalDePortas = this.state.totalDePortas

        if(portaSelecionada > totalDePortas){
            alert('A porta premiada não pode ser maior que o total de portas')
            return false
        } else if(!portaSelecionada){
            alert('Selecione qual será a porta premiada')
            return false
        } else {
            this.setJogoIniciado(e, true)
        }
    }

    render() {
        return (
            <div id="app">
                <h1>Problema de Monty Hall</h1>

                <form className="form">
                    {!this.state.jogoIniciado && (
                        <div>
                            <label htmlFor="totalDePortas">Quantas Portas? </label>
                            <input type="text" id="totalDePortas"
                                onChange={e => this.setTotalDePortas(e)} value={this.state.totalDePortas} />
                        </div>
                    )}

                    {!this.state.jogoIniciado && (
                        <div>
                            <label htmlFor="portaSelecionada">Qual porta é premiada? </label>
                            <input type="text" id="portaSelecionada"
                                onChange={e => this.setPortaSelecionada(e)} />
                        </div>
                    )}

                    {!this.state.jogoIniciado && (
                        <button onClick={e => this.verificarEntradas(e)}>Iniciar</button>
                    )}

                    {this.state.jogoIniciado && (
                        <button onClick={e => this.setJogoIniciado(e, false)}>Reiniciar</button>
                    )}
                    

                </form>

                <div className="portas">
                    {this.state.jogoIniciado && (
                        this.renderizarPortas()
                    )}
                </div>
            </div>
        )
    }
}

// vue/montyhall/src/App.vue
<template>
  <div id="app2">
    <h1>Problema de Monty Hall</h1>
    <div class="form">
      <div v-if="!starded">
        <label for="portsAmount">Quantas portas?</label>
        <input
          type="text"
          id="portsAmount"
          size="3"
          v-model.number="portsAmount"
        />
      </div>
      <div v-if="!starded">
        <label for="selectPort">Qual porta é premiada? </label>
        <input
          type="text"
          id="selectedPort"
          size="3"
          v-model.number="selectedPort"
        />
      </div>
      <button v-if="!starded" @click="checkEntries()">Iniciar</button>
      <button v-if="starded" @click="starded = false">Reiniciar</button>
    </div>
    <div class="doors" v-if="starded">
      <div v-for="i in portsAmount" :key="i">
        <CompDoor :hasGift="i === selectedPort" :number="i" />
      </div>
    </div>
  </div>
</template>

<script>
import CompDoor from "./components/CompDoor.vue";
export default {
  name: "App",
  components: { CompDoor },
  data: function () {
    return {
      starded: false,
      portsAmount: 3,
      selectedPort: null,
    };
  },
  methods: {
   checkEntries() {
      const selectedPort = parseFloat(this.selectedPort);
      const portsAmount = parseFloat(this.portsAmount);

      if (selectedPort > portsAmount) {
        alert("A porta premiada não pode ser maior que o total de portas");
        return false;
      } else if (!selectedPort) {
        alert("Selecione qual será a porta premiada");
        return false;
      } else {
        this.starded = true
      }
    }
  },
};
</script>

<style>
* {
  box-sizing: border-box;
  font-family: "Montserrat" sans-serif;
}

body {
  color: #fff;
  background: linear-gradient(to right, rgb(21, 153, 87), rgb(21, 87, 153));
}

#app2 {
  display: flex;
  flex-direction: column;
  align-items: center;
}

#app2 h1 {
  border: 1px solid #000;
  background-color: #0004;
  padding: 20px;
  margin-bottom: 60px;
}

.form {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  margin-bottom: 40px;
}

.form,
.form input,
.form button {
  margin-bottom: 10px;
  font-size: 2rem;
}

.doors {
  align-self: stretch;
  display: flex;
  justify-content: space-around;
  flex-wrap: wrap;
}
</style>
